### ISSUE TITLE
Inquery the full validation results

### ISSUE THREAD

**Issue by XueZ-phd** [heitorrapela/HalluciDet#1]
Dear author,

This is a good work! Therefore, I would like to cite this paper in my manuscript. 

Could you provide more detailed results (i.e. AP50, AP75, AP50:95) on LLVIP and FLIR datasets? In this case, we can report them directly. 

All the best!

**Comment by heitorrapela** [comment]
Hello @XueZ-phd, thanks for your interest in our work.

Unfortunately, for this work specifically (main paper and support material for WACV2024), we just reported the AP50, and here we run five seeds for each model. But for the entire study on the HalluciDet with three seeds for all APs (i.e., AP50, AP75, AP50:95), I would recommend our follow-up work ([ModTr](https://arxiv.org/pdf/2404.01492)), were we re-run all baselines, and we improved the image-to-image baselines.

The HalluciDet in ModTr paper reported over three seeds and was in a new environment, but the results were a bit superior. The code for this new experiment was done over this repo. As this new work is still a pre-print, It can have some modifications for the camera-ready version, but for the HalluciDet results, you can trust. So, If you want to cite the HalluciDet, you can use our ModTr supp material results and add a footnote saying that these results were done over three seeds provided by the original code.

Full results for HalluciDet can be found on supp material: https://arxiv.org/pdf/2404.01492

![image](https://github.com/heitorrapela/HalluciDet/assets/14017613/9df5493c-c144-44dd-97a1-72ec3afeb3cf)

Let me know if you have any additional questions,

Best Regards,
Heitor Medeiros

**Comment by XueZ-phd** [comment]
Dear Heitor Medeiros,

Thanks for your prompt reply, it saved me a lot of time.

I will report the mean value of HalluciDet in my manuscript: AP50=90.07, AP75=51.23, and AP=57.78.

HalluciDet is really a great work. It has the interesting motivations and good results. I hope more researchers will cite it.

Best Regards,
Xue Zhang

**Comment by heitorrapela** [comment]
> Dear Heitor Medeiros,
> 
> Thanks for your prompt reply, it saved me a lot of time.
> 
> I will report the mean value of HalluciDet in my manuscript: AP50=90.07, AP75=51.23, and AP=57.78.
> 
> HalluciDet is really a great work. It has the interesting motivations and good results. I hope more researchers will cite it.
> 
> Best Regards, Xue Zhang

That sounds good. Thanks for your interest in our work.

I hope more researchers also like it,

Best Regards,
Heitor Medeiros

**Comment by heitorrapela** [comment]
Hi, @XueZ-phd how is going with your manuscript? I hope it is going well. Just to update, for subsequent works if you are still interested in this line of research, our paper ModTr was accepted at ECCV2024, it might be interesting to look on it as well.

Best Regards,
Heitor Medeiros

**Comment by XueZ-phd** [comment]
Hi,@heitorrapela. Congratulations!

Our manuscript has recently been accepted by the IEEE T-NNLS journal. [Here](https://doi.org/10.1109/TNNLS.2024.3443455).

I am very interested in your work. We will focus on it in our follow-up work.

Best Regards,

Xue Zhang

**Comment by heitorrapela** [comment]
Hi @XueZ-phd. 

Congrats on your paper! 

Thanks for the kind words,

Best Regards,
Heitor Medeiros
